rootProject.name = 'spring-integration-instrumentation'
include 'spring-integration-core'
include 'spring-integration-ip'
include 'spring-integration-ws'
include 'spring-integration-core-4.0.0'
include 'spring-integration-core-5.1.0'
include 'spring-integration-core-5.3.0'
include 'spring-integration-ws-4.0.0'
include 'spring-integration-ws-7.0.0'
include 'spring-integration-ip-4.0.0'
include 'spring-integration-ip-7.0.0'
include 'spring-messaging-5.2.0'
include 'spring-messaging-4.0.0'
