
// Build.gradle generated for instrumentation module Spring-Integration-Core-5.3.0

apply plugin: 'java'

targetCompatibility=JavaVersion.VERSION_17

dependencies {
   // Declare a dependency on each JAR you want to instrument
   // Example:
   // implementation 'javax.servlet:servlet-api:2.5'
   implementation 'org.springframework.integration:spring-integration-core:6.4.0'
    implementation 'org.springframework:spring-messaging:6.2.0'

   // New Relic Labs Java Agent dependencies
   implementation 'com.newrelic.agent.java:newrelic-agent:8.4.0'
   implementation 'com.newrelic.agent.java:newrelic-api:8.4.0'
   implementation 'com.newrelic.agent.java:agent-bridge:8.4.0'
   implementation fileTree(include: ['*.jar'], dir: '../test-lib')
}

jar {
  manifest {
    attributes 'Implementation-Title': 'com.newrelic.instrumentation.labs.spring-integration-core-6.4.0'
    attributes 'Implementation-Vendor': 'New Relic Labs'
    attributes 'Implementation-Vendor-Id': 'com.newrelic.labs'
    attributes 'Implementation-Version': 1.0
  }
}

verifyInstrumentation {
  passes 'org.springframework.integration:spring-integration-core:[6.4.0,6.5.0)'
}
