
// Build.gradle generated for instrumentation module Spring-Integration-Core-5.1.0

apply plugin: 'java'

dependencies {
   // Declare a dependency on each JAR you want to instrument
   // Example:
   // implementation 'javax.servlet:servlet-api:2.5'

   implementation 'org.springframework.integration:spring-integration-core:5.1.0.RELEASE'
   implementation 'org.springframework.integration:spring-integration-http:5.1.0.RELEASE'
   implementation 'org.springframework.integration:spring-integration-ws:5.1.0.RELEASE'

   // New Relic Labs Java Agent dependencies
   implementation 'com.newrelic.agent.java:newrelic-agent:' + project.findProperty('java.agent.version')
   implementation 'com.newrelic.agent.java:newrelic-api:' + project.findProperty('java.agent.version')
   implementation 'com.newrelic.agent.java:agent-bridge:8.4.0'
   implementation fileTree(include: ['*.jar'], dir: '../test-lib')
}

jar {
  manifest {
    attributes 'Implementation-Title': 'com.newrelic.instrumentation.labs.Spring-Integration-Core-5.1.0'
    attributes 'Implementation-Vendor': 'New Relic Labs'
    attributes 'Implementation-Vendor-Id': 'com.newrelic.labs'
    attributes 'Implementation-Version': 1.0
  }
}

verifyInstrumentation {
  passesOnly ('org.springframework.integration:spring-integration-core:[5.1.0.RELEASE,5.1.4.RELEASE)')
}
